server.port=${PORT:8080}
spring.application.name=tienda-bolsos
spring.thymeleaf.cache=false
spring.web.resources.cache.period=


spring.datasource.url=${DB_URL:jdbc:mysql://tokaido.proxy.rlwy.net:22300/railway}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:rzRRZDPUVyUaudoZGtDheGvYbBxGALGM}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true


spring.security.user.password= 75265dec-4255-4237-847c-85b08ca7a1da
spring.security.user.name=tiendac


spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.username=${MAIL_USER:sanchez.chvv2@gmail.com}
spring.mail.password=${MAIL_PASSWORD:duci hfwq ekri tnww}


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

